### ISSUE TITLE
"duo toggle" stopped working for Ubuntu 24.10, Kernel 6.11.0-8-generic

### ISSUE THREAD

**Issue by NaScha** [alesya-h/zenbook-duo-2024-ux8406ma-linux#17] opened 2024-10-12 12:18 UTC
I've just upgraded to Ubuntu 24.10 and recognized that "duo toggle" stopped working. This is what is shown in Terminal, but nothing happens to the screens:

`duo toggle
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
Logical monitor [ 2880x1800+0+0 ], PRIMARY, scale = 1.74757
  Monitor [ eDP-1 ] 2880x1800@120
Logical monitor [ 2880x1800+0+1030 ], scale = 1.74757
  Monitor [ eDP-2 ] 2880x1800@120
[(0, 0, 1.7475727796554565, uint32 0, true, [('eDP-1', '2880x1800@120.000', @a{sv} {})]), (0, 1030, 1.7475727796554565, 0, false, [('eDP-2', '2880x1800@120.000', {})])]
`

All the rest is still working like before: rotation, brightness sync. Even duo top, bottom and both are still working. I already know that the WLAN Key Event is not thrown any longer with more recent kernels like the one delivered by the recent Ubuntu Release and so I'm concious that it's no miracle that auto-toggling the lower screen by keyboard attach and detach won't work any longer, but I expected that manual toggling would still be functional.

Is there any way to recover this functionality by changing some settings? BTW: I have already completely removed all this WIFI event triggering stuff - reset dconf setting and also deleted the keyboard event described in the ReadMe.

**Comment by SchoeningStud** [comment] 2024-10-14 17:55
This is probably caused by the unknown display registered in the newer kernel versions. Since the toggle command only checks for disabled monitors, this will cause it to only run "duo both".

Changing "gnome-monitor-config list | grep OFF" to "gnome-monitor-config list | grep OFF | grep eDP" in the toggle command should fix this.

**Comment by alesya-h** [comment] 2024-10-21 06:51
fixed in f4babe6 , thank you

**Closed as completed by alesya-h** 2024-10-21 06:51 UTC
